logging:
  level:
    root: INFO
    com.smartpayment.nxt: DEBUG
    com.smartpayment.nxt.hierarchy: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    reactor.netty.http.client.HttpClientConnect: DEBUG

spring:
  datasource:
    dbname: n360_dev
    username: dev_hierarchy
    password: eiJfGs3CTYjKV5
    host: localhost
    port: 5432
    host_ro: localhost
    port_ro: 5430
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

webclient:
  client:
    nxt-msa-users:
      base-url: https://api.dev.stg.smartpayment.com.mx/users/api
      connect-timeout: 30000
      read-timeout: 5000
      write-timeout: 5000
    nxt-msa-logger:
      base-url: http://localhost:8415
      elasticSearchInsertPath: /api/elasticsearch/insert/prueba
      messaging-response-code-path: /api/messaging/response-code
      connect-timeout: 30000
      read-timeout: 5000
      write-timeout: 5000
      module: hierarchy-parameters
