spring:
  application:
    name: hierarchy-parameters
  datasource:
    driver-class-name: org.postgresql.Driver
  profiles:
    active: dev

server:
  port: 9891

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    env:
      show-values: ALWAYS
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
    version: OPENAPI_3_1
  swagger-ui:
    disable-swagger-default-url: true
    path: /hierarchy-parameters
