logging:
  level:
    root: INFO
    com.smartpayment.nxt: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    reactor.netty.http.client.HttpClientConnect: DEBUG

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

secret:
  name: sps-prod-secret-hierarchy-parameters

webclient:
  client:
    nxt-msa-users:
      base-url: http://msa-prod-nxt-svc-users:40003/api
      connect-timeout: 30000
      read-timeout: 5000
      write-timeout: 5000
    nxt-msa-logger:
      base-url: http://msa-prod-nxt-svc-logger:40006
      elasticSearchInsertPath: /api/elasticsearch/insert/prueba
      messaging-response-code-path: /api/messaging/response-code
      connect-timeout: 30000
      read-timeout: 5000
      write-timeout: 5000
      module: hierarchy-parameters
